### ISSUE TITLE
not displaying correctly

### ISSUE THREAD

**Issue by artofwalls** [Jon-Salmon/View-Image-Resurrected#1] opened 2018-02-21 22:46 UTC
There is something that is not working correctly with the add on. the drop down arrow appears under the button instead of being part of the right side of it. And when I click the arrow, the copy option appears but the download option is behind the text and the miniatures of the related images. I suppose the reason has something to do with the "Guardar" (save) and "ver Guardadas" (see saved) buttons that appear in my Google Images. Also, the buttons appear taller than before, probably because some text is broken into two lines.

![captura de pantalla 2018-02-21 22 38 57](https://user-images.githubusercontent.com/18701653/36509661-47bda560-1758-11e8-9686-11c447994001.png)

**Comment by artofwalls** [comment] 2018-02-21 22:48
Here is how it appears without the Add on (but also without the button that Google removed):

![captura de pantalla 2018-02-21 22 47 55](https://user-images.githubusercontent.com/18701653/36509958-51b14b16-1759-11e8-9a69-a59eb3591866.png)

**Comment by Jon-Salmon** [comment] 2018-02-22 00:29
Thankyou for raising this, It is caused by how i've added the drop down component. I'll see if i can put a patch together for it!

**Comment by Jon-Salmon** [comment] 2018-02-22 02:00
Added provisional fix, closing issue for now

**Closed as completed by Jon-Salmon** 2018-02-22 02:00 UTC

**Comment by artofwalls** [comment] 2018-02-22 02:47
Now it displays great!
Thank you! 

![captura de pantalla 2018-02-22 02 46 51](https://user-images.githubusercontent.com/18701653/36517609-c0f5005a-177a-11e8-8fea-9b6a68c39bb3.png)
